Bring changes from onedr0p's repo. :D

diff --git a/.github/workflows/action-image-build.yaml b/.github/workflows/action-image-build.yaml
--- a/.github/workflows/action-image-build.yaml
+++ b/.github/workflows/action-image-build.yaml
@@ -26,193 +26,242 @@ on:
         default: 'false'
         type: string
 
-      updateMetadata:
-        required: false
-        default: 'false'
-        type: string
-
       sendNotification:
         required: false
         default: 'false'
         type: string
 
-env:
-  IMAGE_REGISTRY_GHCR: ghcr.io
-
 jobs:
-  build-and-test:
-    name: Build and test
-    #runs-on: ["self-hosted", "X64"]
+  prepare:
+    name: Prepare Matrices
     runs-on: ubuntu-latest
-    if: inputs.imagesToBuild != '' && inputs.imagesToBuild != '[]'
-    strategy:
-      matrix:
-        image: ["${{ fromJson(inputs.imagesToBuild) }}"]
-      fail-fast: false
+    outputs:
+      matrices: ${{ steps.generate-matrices.outputs.matrices }}
+    if: ${{ inputs.imagesToBuild != '' && inputs.imagesToBuild != '[]' }}
     steps:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 1
 
-      - name: Setup workflow Variables
-        id: vars
-        shell: bash
-        run: |-
-          container_base=$(jq '.base' ./apps/${{ matrix.image.app }}/metadata.json)
-          echo "chan_build_date=$(date --rfc-3339=seconds --utc)" >> $GITHUB_OUTPUT
-
-          chan_config=$(jq --arg chan "${{ matrix.image.channel }}" '(.channels | .[] | select(.name == $chan))' ./apps/${{ matrix.image.app }}/metadata.json)
-          chan_stable=$(jq --raw-output '.stable' <<< "${chan_config}")
-
-          chan_platforms=$(jq --raw-output '.platforms | join(",")' <<< "${chan_config}") && \
-              echo "chan_platforms=${chan_platforms}" >> $GITHUB_OUTPUT
-          chan_tests_enabled=$(jq --raw-output '.tests.enabled' <<< "${chan_config}") && \
-              echo "chan_tests_enabled=${chan_tests_enabled}" >> $GITHUB_OUTPUT
-          chan_tests_type=$(jq --raw-output '.tests.type' <<< "${chan_config}") && \
-              echo "chan_tests_type=${chan_tests_type}" >> $GITHUB_OUTPUT
-
-          chan_upstream_version=$(bash ./.github/scripts/upstream.sh "${{ matrix.image.app }}" "${{ matrix.image.channel }}") && \
-              echo "chan_upstream_version=${chan_upstream_version}" >> $GITHUB_OUTPUT
-
-          if [[ "${chan_tests_enabled}" == true && "${chan_tests_type}" == "cli" ]]; then
-              echo "chan_goss_args=tail -f /dev/null" >> $GITHUB_OUTPUT
-          fi
-
-          if [[ "${container_base}" == true ]]; then
-              echo "chan_label_type=org.opencontainers.image.base" >> $GITHUB_OUTPUT
-          else
-              echo "chan_label_type=org.opencontainers.image" >> $GITHUB_OUTPUT
-          fi
-
-          if test -f "./apps/${{ matrix.image.app }}/${{ matrix.image.channel }}/Dockerfile"; then
-              echo "chan_dockerfile=./apps/${{ matrix.image.app }}/${{ matrix.image.channel }}/Dockerfile" >> $GITHUB_OUTPUT
-              echo "chan_goss_config=./apps/${{ matrix.image.app }}/${{ matrix.image.channel }}/goss.yaml" >> $GITHUB_OUTPUT
-          else
-              echo "chan_dockerfile=./apps/${{ matrix.image.app }}/Dockerfile" >> $GITHUB_OUTPUT
-              echo "chan_goss_config=./apps/${{ matrix.image.app }}/ci/goss.yaml" >> $GITHUB_OUTPUT
-          fi
-
-          if [[ "${chan_stable}" == true ]]; then
-              echo "chan_tag_rolling=${{ matrix.image.app }}:rolling" >> $GITHUB_OUTPUT
-              echo "chan_tag_version=${{ matrix.image.app }}:${chan_upstream_version}" >> $GITHUB_OUTPUT
-          else
-              echo "chan_tag_rolling=${{ matrix.image.app }}-${{ matrix.image.channel }}:rolling" >> $GITHUB_OUTPUT
-              echo "chan_tag_version=${{ matrix.image.app }}-${{ matrix.image.channel }}:${chan_upstream_version}" >> $GITHUB_OUTPUT
-          fi
-
-      # https://github.com/redhat-actions/buildah-build/issues/100
-      - name: Setup Tools
-        shell: bash
+      - name: Log images to build
         run: |
-          echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/ /' | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:unstable.list
-          curl -fsSL https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/unstable/xUbuntu_22.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/devel_kubic_libcontainers_unstable.gpg > /dev/null
-          sudo apt-get update
-          sudo apt-get install -y moreutils jo qemu-user-static
-          sudo apt-get install -y buildah -o Dpkg::Options::="--force-overwrite"
+          echo 'imagesToBuild=${{ inputs.imagesToBuild }}'
+          echo 'pushImages=${{ inputs.pushImages }}'
+          echo 'sendNotification=${{ inputs.sendNotification }}'
 
       - name: Setup CUE
-        uses: cue-lang/setup-cue@v1.0.0-alpha.2
+        uses: cue-lang/setup-cue@0be332bb74c8a2f07821389447ba3163e2da3bfb
 
-      - name: Setup Goss
-        if: ${{ steps.vars.outputs.chan_tests_enabled == 'true' }}
-        uses: e1himself/goss-installation-action@v1.1.0
-        with:
-          # renovate: datasource=github-releases depName=aelsabbahy/goss
-          version: v0.3.20
-
-      - name: Validate image metadata
+      - name: Validate Image Metadata
         shell: bash
-        run: |-
-          cue vet --schema '#Spec' ./apps/${{ matrix.image.app }}/metadata.json ./metadata.rules.cue
+        # 'xargs' rather than 'find -exec' so we can capture the status code
+        run: |
+          find ./apps/ -name metadata.json | xargs -I {} cue vet --schema '#Spec' {} ./metadata.rules.cue
 
-      - name: Build all platforms
-        id: build_image
-        uses: redhat-actions/buildah-build@v2.12
+      - name: Generate Matrices
+        id: generate-matrices
+        run: |
+          matrices=$(./.github/scripts/prepare-images.py '${{ inputs.imagesToBuild }}' '${{ inputs.pushImages }}')
+          echo "matrices=${matrices}" >> $GITHUB_OUTPUT
+
+  build-platform-images:
+    name: Build/Test ${{ matrix.image.chan_image_name }} - ${{ matrix.image.platform }}
+    runs-on: ubuntu-latest
+    needs:
+      - prepare
+    strategy:
+      matrix:
+        image: ["${{ fromJson(needs.prepare.outputs.matrices).imagePlatformPermutations }}"]
+      fail-fast: false
+    steps:
+      - name: Log Matrix Input
+        run: |
+          cat << EOF
+          ${{ toJSON(matrix.image) }}
+          EOF
+      - uses: actions/checkout@v3
         with:
-          build-args: |-
-            VERSION=${{ steps.vars.outputs.chan_upstream_version }}
-            CHANNEL=${{ matrix.image.channel }}
-          platforms: ${{ steps.vars.outputs.chan_platforms }}
-          context: .
-          containerfiles: |
-            ${{ steps.vars.outputs.chan_dockerfile }}
-          layers: true
-          tags: |-
-            ${{ env.IMAGE_REGISTRY_GHCR }}/${{ github.repository_owner }}/${{ steps.vars.outputs.chan_tag_rolling }}
-            ${{ env.IMAGE_REGISTRY_GHCR }}/${{ github.repository_owner }}/${{ steps.vars.outputs.chan_tag_version }}
-          labels: |-
-            ${{ steps.vars.outputs.chan_label_type }}.created="${{ steps.vars.outputs.chan_build_date }}"
-            ${{ steps.vars.outputs.chan_label_type }}.title="${{ matrix.image.app }} (${{ matrix.image.channel }})"
-            ${{ steps.vars.outputs.chan_label_type }}.version="${{ steps.vars.outputs.chan_upstream_version }}"
-            ${{ steps.vars.outputs.chan_label_type }}.authors="Skyler Mäntysaari <sm+git@samipsolutions.fi>"
-            ${{ steps.vars.outputs.chan_label_type }}.url="https://github.com/samipsolutions/containers/apps/${{ matrix.image.app }}"
-            ${{ steps.vars.outputs.chan_label_type }}.build.url="https://github.com/samipsolutions/containers/actions/runs/${{ github.run_id }}"
-            ${{ steps.vars.outputs.chan_label_type }}.documentation="https://github.com/samipsolutions/containers/apps/${{ matrix.image.app }}/README.md"
-            ${{ steps.vars.outputs.chan_label_type }}.revision="${{ github.sha }}"
+          fetch-depth: 1
 
-      - name: Run Goss tests
-        id: dgoss
-        if: ${{ steps.vars.outputs.chan_tests_enabled == 'true' }}
-        shell: bash
-        env:
-          CONTAINER_RUNTIME: podman
-          GOSS_FILE: ${{ steps.vars.outputs.chan_goss_config }}
-          GOSS_OPTS: |-
-            --sleep 5s --retry-timeout 60s --color --format documentation
-          GOSS_SLEEP: 2
-          GOSS_FILES_STRATEGY: cp
-          CONTAINER_LOG_OUTPUT: goss_container_log_output
-        run: >
-          dgoss run ${{ env.IMAGE_REGISTRY_GHCR }}/${{ github.repository_owner }}/${{ steps.vars.outputs.chan_tag_rolling }} ${{ steps.vars.outputs.chan_goss_args }}
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
 
-      - name: Push To GHCR
-        id: push_to_ghcr
-        if: ${{ inputs.pushImages == 'true' }}
-        uses: redhat-actions/push-to-registry@v2.7
+      - name: Setup GHCR
+        uses: docker/login-action@v2
         with:
-          image: ${{ steps.build_image.outputs.image }}
-          tags: ${{ steps.build_image.outputs.tags }}
-          registry: ${{ env.IMAGE_REGISTRY_GHCR }}/${{ env.IMAGE_NAMESPACE }}
+          registry: ghcr.io
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Setup Tools
+        shell: bash
+        run: sudo apt-get install -y moreutils jo
+
+      - name: Setup Goss
+        if: ${{ matrix.image.chan_tests_enabled }}
+        uses: e1himself/goss-installation-action@v1.1.0
+        with:
+          version: v0.3.21
+
+      - name: Prepare Build Outputs
+        id: prepare-build-outputs
+        run: |
+          if [[ ${{ inputs.pushImages }} == 'true' ]]; then
+              image_name="ghcr.io/${{ github.repository_owner }}/${{ matrix.image.chan_image_name }}"
+              outputs="type=image,name=${image_name},push-by-digest=true,name-canonical=true,push=true"
+          else
+              image_name="ghcr.io/${{ github.repository_owner }}/${{ matrix.image.chan_tag_testing }}"
+              outputs="type=docker,name=${image_name},push=false"
+          fi
+          echo "image_name=${image_name}" >> $GITHUB_OUTPUT
+          echo "outputs=${outputs}" >> $GITHUB_OUTPUT
+
+      - name: Build Image
+        uses: docker/build-push-action@v4
+        id: build
+        with:
+          build-args: |-
+            VERSION=${{ matrix.image.chan_upstream_version }}
+            CHANNEL=${{ matrix.image.channel }}
+          context: .
+          platforms: ${{ matrix.image.platform }}
+          file: ${{ matrix.image.chan_dockerfile }}
+          outputs: ${{ steps.prepare-build-outputs.outputs.outputs }}
+          cache-from: type=gha
+          cache-to: type=gha,mode=max
+
+      - name: Run Goss Tests
+        id: dgoss
+        if: ${{ matrix.image.chan_tests_enabled }}
+        shell: bash
+        env:
+          CONTAINER_RUNTIME: docker
+          GOSS_FILE: ${{ matrix.image.chan_goss_config }}
+          GOSS_OPTS: --retry-timeout 60s --sleep 2s --color --format documentation
+          GOSS_SLEEP: 2
+          GOSS_FILES_STRATEGY: cp
+          CONTAINER_LOG_OUTPUT: goss_container_log_output
+        run: |
+          if [[ '${{ inputs.pushImages }}' == 'true' ]]; then
+              image_name="${{ steps.prepare-build-outputs.outputs.image_name }}@${{ steps.build.outputs.digest }}"
+          else
+              image_name="${{ steps.prepare-build-outputs.outputs.image_name }}"
+          fi
+          dgoss run ${image_name} ${{ matrix.image.chan_goss_args }}
+
+      - name: Export Digest
+        id: export-digest
+        if: ${{ inputs.pushImages == 'true' }}
+        run: |
+          mkdir -p /tmp/${{ matrix.image.chan_image_name }}/digests
+          digest="${{ steps.build.outputs.digest }}"
+          echo "${{ matrix.image.platform }}" > "/tmp/${{ matrix.image.chan_image_name }}/digests/${digest#sha256:}"
+
+      - name: Upload Digest
+        if: ${{ inputs.pushImages == 'true' }}
+        uses: actions/upload-artifact@v3
+        with:
+          name: ${{ matrix.image.chan_image_name }}
+          path: /tmp/${{ matrix.image.chan_image_name }}/*
+          if-no-files-found: error
+          retention-days: 1
+
+  merge:
+    name: Merge ${{ matrix.manifest.image }}
+    runs-on: ubuntu-latest
+    needs:
+      - prepare
+      - build-platform-images
+    # Always run merge, as the prior matrix is all or nothing. We test for prior step failure
+    # in the "Test Failed Bit" step. This ensures if one app fails, others can still complete.
+    if: ${{ always() && inputs.pushImages == 'true'}}
+    strategy:
+      matrix:
+        manifest: ["${{ fromJSON(needs.prepare.outputs.matrices).manifestsToBuild }}"]
+      fail-fast: false
+    steps:
+      - name: Download Digests
+        uses: actions/download-artifact@v3
+        with:
+          name: ${{ matrix.manifest.image }}
+          path: /tmp/${{ matrix.manifest.image }}
+
+      - name: Ensure all platforms were built
+        id: ensure-platforms
+        run: |
+          EXPECTED_COUNT=$(cat << EOF | jq ". | length"
+          ${{ toJSON(matrix.manifest.platforms) }}
+          EOF
+          )
+          ACTUAL_COUNT=$(ls -1 /tmp/${{ matrix.manifest.image }}/digests | wc -l)
+          if [[ $EXPECTED_COUNT != $ACTUAL_COUNT ]]; then
+              echo "Expected $EXPECTED_COUNT platforms, but only found $ACTUAL_COUNT"
+              echo "Expected: ${{ toJSON(matrix.manifest.platforms) }}"
+              echo "Actual: $(cat /tmp/${{ matrix.manifest.image }}/digests/*)"
+              exit 1
+          fi
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Setup GHCR
+        uses: docker/login-action@v2
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+
+      - name: Log Files
+        working-directory: /tmp/${{ matrix.manifest.image }}/digests
+        run: |
+          ls -la
+          cat *
+
+      # https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
+      - name: Merge Manifests
+        id: merge
+        working-directory: /tmp/${{ matrix.manifest.image }}/digests
+        env:
+          TAGS: ${{ toJSON(matrix.manifest.tags) }}
+        run: |
+          docker buildx imagetools create $(jq -cr '. | map("-t ghcr.io/${{ github.repository_owner }}/" + .) | join(" ")'  <<< "$TAGS") \
+              $(printf 'ghcr.io/${{ github.repository_owner }}/${{ matrix.manifest.image }}@sha256:%s ' *)
+
+      - name: Inspect image
+        run: |
+          docker buildx imagetools inspect ghcr.io/${{ github.repository_owner }}/${{ matrix.manifest.image }}:${{ matrix.manifest.version }}
+
       - name: Build successful
         id: build-success
-        if: ${{ always() && steps.build_image.outcome == 'success' && steps.dgoss.outcome == 'success' && (steps.push_to_ghcr.outcome == 'success' || steps.push_to_ghcr.outcome == 'skipped') }}
+        if: ${{ always() && steps.merge.outcome == 'success' && steps.failure-test.outcome == 'success' }}
         run: |-
-          echo "message=🎉 ${{ matrix.image.app }}-${{ matrix.image.channel }} (${{ steps.vars.outputs.chan_upstream_version }})" >> $GITHUB_OUTPUT
+          echo "message=🎉 ${{ matrix.manifest.app }}-${{ matrix.manifest.channel }} (${{ matrix.manifest.version }})" >> $GITHUB_OUTPUT
           echo "color=0x00FF00" >> $GITHUB_OUTPUT
-          echo "::group::Container log output"
-          cat "goss_container_log_output"
-          echo "::endgroup::"
 
       - name: Build failed
         id: build-failed
-        if: ${{ always() && (steps.build_image.outcome == 'failure' || steps.dgoss.outcome == 'failure' || steps.push_to_ghcr.outcome == 'failure') }}
+        if: ${{ always() && (steps.merge.outcome == 'failure' || steps.failure-test.outcome == 'failure') }}
         run: |-
-          echo "message=💥 ${{ matrix.image.app }}-${{ matrix.image.channel }} (${{ steps.vars.outputs.chan_upstream_version }})" >> $GITHUB_OUTPUT
+          echo "message=💥 ${{ matrix.manifest.app }}-${{ matrix.manifest.channel }} (${{ matrix.manifest.version }})" >> $GITHUB_OUTPUT
           echo "color=0xFF0000" >> $GITHUB_OUTPUT
-          echo "::group::Container log output"
-          cat "goss_container_log_output"
-          echo "::endgroup::"
 
-      #- name: Send Discord Webhook
-      #  uses: sarisia/actions-status-discord@v1
-      #  if: ${{ always() && inputs.sendNotification == 'true' }}
-      #  with:
-      #    webhook: ${{ secrets.DISCORD_WEBHOOK }}
-      #    title: ${{ steps.build-failed.outputs.message || steps.build-success.outputs.message }}
-      #    color: ${{ steps.build-failed.outputs.color }}
-      #    username: GitHub Actions
+      - name: Send Discord Webhook
+        uses: sarisia/actions-status-discord@v1
+        if: ${{ always() && inputs.sendNotification == 'true' }}
+        with:
+          webhook: ${{ secrets.DISCORD_WEBHOOK }}
+          title: ${{ steps.build-failed.outputs.message || steps.build-success.outputs.message }}
+          color: ${{ steps.build-failed.outputs.color || steps.build-success.outputs.color }}
+          username: GitHub Actions
 
   # Summarize matrix https://github.community/t/status-check-for-a-matrix-jobs/127354/7
   build_success:
     name: Build matrix success
-    runs-on: ubuntu-22.04
+    runs-on: ubuntu-latest
     needs:
-      - build-and-test
+      - merge
     if: ${{ always() }}
     steps:
       - name: Check build matrix status
-        if: ${{ (inputs.imagesToBuild != '' && inputs.imagesToBuild != '[]') && (needs.build-and-test.result != 'success') }}
+        if: ${{ (inputs.imagesToBuild != '' && inputs.imagesToBuild != '[]') && (needs.merge.result != 'success' && needs.merge.result != 'skipped') }}
         run: exit 1
